### ISSUE TITLE
Audit PDF typo?

### ISSUE THREAD

**Issue by EvanWinget** [ariard/validating-lightning-signer#1]
Hi @ariard - I noticed that the first sentence in the audit report mentions that the audit is based on the state of the VLS repo in January 2022.

I believe that this is a typo and that it should instead say January 2023. Sorry that I have not PR'ed a fix myself, given that it is a PDF.

**Comment by ariard** [comment]
Thanks for the catch! Effectively January 2023. Should be addressed with #2 fixing other typos flagged.
